#!/bin/sh -e

muon setup \
    -Dprefix=/usr \
    -Dlibexecdir=/usr/lib \
    -Denable-docs=false \
    -Denable-wayland=true \
    -Denable-x11=false \
    -Denable-xkbregistry=false \
    output

ninja -C output
muon  -C output install
