#!/bin/sh -e

patch -p1 < libinput-1.31.patch

export DESTDIR="$1"

meson setup \
    -Dprefix=/usr \
    -Ddefault_library=both \
    -Dexamples=false \
    -Dxcb-errors=disabled \
    -Drenderers=gles2 \
    build

ninja -C build
ninja -C build install
