#!/bin/sh -e

muon setup \
    -Dprefix=/usr \
    -Dbuildtype=release \
    -Dforce_fallback_for=tllist \
    -Djpeg=enabled \
    -Dpng=enabled \
    output

ninja -C output
muon  -C output install
