#!/bin/sh -e

muon setup \
    -Dprefix=/usr \
    -Dbuildtype=release \
    -Dforce_fallback_for=fcft,tllist \
    -Dime=false \
    output

ninja -C output
muon  -C output install

rm -rf \
    "$1/usr/share/doc" \
    "$1/usr/share/zsh" \
    "$1/usr/share/fish" \
    "$1/usr/share/bash-completion"
