#!/bin/sh -e

muon setup \
    -Dprefix=/usr \
    -Dsysconfdir=/etc \
    -Dmandir=/usr/share/man \
    -Dwith_wayland=yes \
    -Dwith_x11=no \
    -Dwith_glx=no \
    output

ninja -C output
muon  -C output install
