#!/bin/sh -e

patch -p1 < no-fribidi.patch

# Muon doesn't support gnome module.
patch -p1 < muon.patch

: > tests/meson.build
: > examples/meson.build
: > docs/meson.build

muon setup \
    -Dprefix=/usr \
    -Dgtk_doc=false \
    -Dxft=disabled \
    -Dintrospection=disabled \
    -Dwrap_mode=nofallback \
    build

ninja -C build
muon  -C build install
